# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.30.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/armaine/documents/Week2-OSEmulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/armaine/documents/Week2-OSEmulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.30.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/armaine/documents/Week2-OSEmulator/CMakeFiles /Users/armaine/documents/Week2-OSEmulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/armaine/documents/Week2-OSEmulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/armaine/documents/Week2-OSEmulator/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sim

# Build rule for target.
sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sim
.PHONY : sim

# fast build rule for target.
sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/build
.PHONY : sim/fast

src/commands.o: src/commands.cpp.o
.PHONY : src/commands.o

# target to build an object file
src/commands.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/commands.cpp.o
.PHONY : src/commands.cpp.o

src/commands.i: src/commands.cpp.i
.PHONY : src/commands.i

# target to preprocess a source file
src/commands.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/commands.cpp.i
.PHONY : src/commands.cpp.i

src/commands.s: src/commands.cpp.s
.PHONY : src/commands.s

# target to generate assembly for a file
src/commands.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/commands.cpp.s
.PHONY : src/commands.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/console.o: src/console.cpp.o
.PHONY : src/console.o

# target to build an object file
src/console.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/console.cpp.o
.PHONY : src/console.cpp.o

src/console.i: src/console.cpp.i
.PHONY : src/console.i

# target to preprocess a source file
src/console.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/console.cpp.i
.PHONY : src/console.cpp.i

src/console.s: src/console.cpp.s
.PHONY : src/console.s

# target to generate assembly for a file
src/console.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/console.cpp.s
.PHONY : src/console.cpp.s

src/dispatcher.o: src/dispatcher.cpp.o
.PHONY : src/dispatcher.o

# target to build an object file
src/dispatcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/dispatcher.cpp.o
.PHONY : src/dispatcher.cpp.o

src/dispatcher.i: src/dispatcher.cpp.i
.PHONY : src/dispatcher.i

# target to preprocess a source file
src/dispatcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/dispatcher.cpp.i
.PHONY : src/dispatcher.cpp.i

src/dispatcher.s: src/dispatcher.cpp.s
.PHONY : src/dispatcher.s

# target to generate assembly for a file
src/dispatcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/dispatcher.cpp.s
.PHONY : src/dispatcher.cpp.s

src/evaluator.o: src/evaluator.cpp.o
.PHONY : src/evaluator.o

# target to build an object file
src/evaluator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/evaluator.cpp.o
.PHONY : src/evaluator.cpp.o

src/evaluator.i: src/evaluator.cpp.i
.PHONY : src/evaluator.i

# target to preprocess a source file
src/evaluator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/evaluator.cpp.i
.PHONY : src/evaluator.cpp.i

src/evaluator.s: src/evaluator.cpp.s
.PHONY : src/evaluator.s

# target to generate assembly for a file
src/evaluator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/evaluator.cpp.s
.PHONY : src/evaluator.cpp.s

src/instruction_generator.o: src/instruction_generator.cpp.o
.PHONY : src/instruction_generator.o

# target to build an object file
src/instruction_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/instruction_generator.cpp.o
.PHONY : src/instruction_generator.cpp.o

src/instruction_generator.i: src/instruction_generator.cpp.i
.PHONY : src/instruction_generator.i

# target to preprocess a source file
src/instruction_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/instruction_generator.cpp.i
.PHONY : src/instruction_generator.cpp.i

src/instruction_generator.s: src/instruction_generator.cpp.s
.PHONY : src/instruction_generator.s

# target to generate assembly for a file
src/instruction_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/instruction_generator.cpp.s
.PHONY : src/instruction_generator.cpp.s

src/instruction_parser.o: src/instruction_parser.cpp.o
.PHONY : src/instruction_parser.o

# target to build an object file
src/instruction_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/instruction_parser.cpp.o
.PHONY : src/instruction_parser.cpp.o

src/instruction_parser.i: src/instruction_parser.cpp.i
.PHONY : src/instruction_parser.i

# target to preprocess a source file
src/instruction_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/instruction_parser.cpp.i
.PHONY : src/instruction_parser.cpp.i

src/instruction_parser.s: src/instruction_parser.cpp.s
.PHONY : src/instruction_parser.s

# target to generate assembly for a file
src/instruction_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/instruction_parser.cpp.s
.PHONY : src/instruction_parser.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/process_control_block.o: src/process_control_block.cpp.o
.PHONY : src/process_control_block.o

# target to build an object file
src/process_control_block.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/process_control_block.cpp.o
.PHONY : src/process_control_block.cpp.o

src/process_control_block.i: src/process_control_block.cpp.i
.PHONY : src/process_control_block.i

# target to preprocess a source file
src/process_control_block.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/process_control_block.cpp.i
.PHONY : src/process_control_block.cpp.i

src/process_control_block.s: src/process_control_block.cpp.s
.PHONY : src/process_control_block.s

# target to generate assembly for a file
src/process_control_block.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/process_control_block.cpp.s
.PHONY : src/process_control_block.cpp.s

src/scheduler.o: src/scheduler.cpp.o
.PHONY : src/scheduler.o

# target to build an object file
src/scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/scheduler.cpp.o
.PHONY : src/scheduler.cpp.o

src/scheduler.i: src/scheduler.cpp.i
.PHONY : src/scheduler.i

# target to preprocess a source file
src/scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/scheduler.cpp.i
.PHONY : src/scheduler.cpp.i

src/scheduler.s: src/scheduler.cpp.s
.PHONY : src/scheduler.s

# target to generate assembly for a file
src/scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/scheduler.cpp.s
.PHONY : src/scheduler.cpp.s

src/screen.o: src/screen.cpp.o
.PHONY : src/screen.o

# target to build an object file
src/screen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/screen.cpp.o
.PHONY : src/screen.cpp.o

src/screen.i: src/screen.cpp.i
.PHONY : src/screen.i

# target to preprocess a source file
src/screen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/screen.cpp.i
.PHONY : src/screen.cpp.i

src/screen.s: src/screen.cpp.s
.PHONY : src/screen.s

# target to generate assembly for a file
src/screen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sim.dir/build.make CMakeFiles/sim.dir/src/screen.cpp.s
.PHONY : src/screen.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sim"
	@echo "... src/commands.o"
	@echo "... src/commands.i"
	@echo "... src/commands.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/console.o"
	@echo "... src/console.i"
	@echo "... src/console.s"
	@echo "... src/dispatcher.o"
	@echo "... src/dispatcher.i"
	@echo "... src/dispatcher.s"
	@echo "... src/evaluator.o"
	@echo "... src/evaluator.i"
	@echo "... src/evaluator.s"
	@echo "... src/instruction_generator.o"
	@echo "... src/instruction_generator.i"
	@echo "... src/instruction_generator.s"
	@echo "... src/instruction_parser.o"
	@echo "... src/instruction_parser.i"
	@echo "... src/instruction_parser.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/process_control_block.o"
	@echo "... src/process_control_block.i"
	@echo "... src/process_control_block.s"
	@echo "... src/scheduler.o"
	@echo "... src/scheduler.i"
	@echo "... src/scheduler.s"
	@echo "... src/screen.o"
	@echo "... src/screen.i"
	@echo "... src/screen.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/armaine/documents/Week2-OSEmulator/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

